CREATE TABLE blog(	
	id		INTEGER      	PRIMARY KEY,
	username	VARCHAR (20) 	NOT NULL,
	password	VARCHAR (20) 	NOT NULL,
	subject		VARCHAR (100)  	NOT NULL,
	email		VARCHAR (50)  	NOT NULL,
	image		VARCHAR (100)  	NULL,
	visitcount	INTEGER    	NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE sort(	
	id		INTEGER      	PRIMARY KEY,
	name		VARCHAR (40) 	NOT NULL,
	blogid		INTEGER		NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE article(	
	id 		INTEGER    	PRIMARY KEY,
	title 		VARCHAR (20) 	NOT NULL ,
	content		TEXT(2000) 	NULL,
	pubtime		DATETIME	NOT NULL,
	blogid		INTEGER		NOT NULL,
	sortid 		INTEGER		NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE feedback(	
	id 		INTEGER    	PRIMARY KEY,
	uname		VARCHAR (20) 	NOT NULL ,
	content		TEXT(2000) 	NULL,
	pubtime		DATETIME 	NOT NULL,
	articleid	INTEGER
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE links(	
	id		INTEGER      	PRIMARY KEY,
	name		VARCHAR (40) 	NOT NULL,
	url		VARCHAR (100) 	NOT NULL,
	blogid		INTEGER		NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;



