/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.bdsoft.test.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

//import org.apache.struts.action.Action;
//import org.apache.struts.action.ActionForm;
//import org.apache.struts.action.ActionForward;
//import org.apache.struts.action.ActionMapping;

import com.bdsoft.test.dao.TreeDao;


public class GetTreeAction {// extends Action {

//	public ActionForward execute(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		TreeDao dao = new TreeDao();
//		List noteList = dao.getParents(); 
//		request.setAttribute("list", noteList); 
//		return new ActionForward("/jsp1009/tree.jsp");
//	}
}