/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.bdsoft.test.action;

import java.io.PrintWriter;
import java.util.Iterator;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

//import org.apache.struts.action.ActionForm;
//import org.apache.struts.action.ActionForward;
//import org.apache.struts.action.ActionMapping;
//import org.apache.struts.actions.DispatchAction;

import com.bdsoft.test.dao.AjaxDao;
import com.bdsoft.test.pojo.StuInfo;
import com.bdsoft.test.pojo.Class;

public class LoadAction {//extends DispatchAction {

//	public ActionForward loadClass(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		System.out.println("loadClass");
//		AjaxDao dao = new AjaxDao();
//		response.setContentType("text/xml");
//		response.setCharacterEncoding("utf-8");
//		Iterator ite = (dao.loadClass()).iterator();
//		try {
//			PrintWriter out = response.getWriter();
//			out.print("<response>");
//			while (ite.hasNext()) {
//				Class cls = (Class) ite.next();
//				out.print("<cls>");
//				out.print("<clsname>" + cls.getCname() + "</clsname>");
//				out.print("<clsvalue>" + cls.getCid() + "</clsvalue>");
//				out.print("</cls>");
//			}
//			out.print("</response>");
//			out.flush();
//			out.close();
//		} catch (Exception se) {
//		}
//		return null;
//	}
//
//	public ActionForward loadStu(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		AjaxDao dao = new AjaxDao();
//		System.out.println("loadStu");
//		response.setContentType("text/xml");
//		response.setCharacterEncoding("utf-8");
//		String cid = request.getParameter("cid");
//		Iterator ite = (dao.loadStu(cid)).iterator();
//		try {
//			PrintWriter out = response.getWriter();
//			out.print("<response>");
//			while (ite.hasNext()) {
//				StuInfo stu = (StuInfo) ite.next();
//				out.print("<stu>");
//				out.print("<stuname>" + stu.getSname() + "</stuname>");
//				out.print("<stuvalue>" + stu.getSid() + "</stuvalue>");
//				out.print("</stu>");
//			}
//			out.print("</response>");
//			out.flush();
//			out.close();
//		} catch (Exception se) {
//		}
//		return null;
//	}
}